# -*- coding: utf-8 -*-
"""health_predictor.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NoMAT6tGRDRhoVxGBuOI_aWxjKsxigiI
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import joblib  # Fixed typo here

# 1. Create simple data (BMI vs Health Score 0-100)
data = {'bmi': [18, 21, 24, 27, 30, 35], 'score': [90, 95, 85, 70, 50, 30]}
df = pd.DataFrame(data)

# 2. Train the Model
model = LinearRegression()
model.fit(df[['bmi']], df['score'])

# 3. Save the model
joblib.dump(model, 'health_model.pkl') # Fixed typo here
print("Model trained and saved successfully!")